### ISSUE TITLE
WSO2 container fails with "Couldn't initialize the ESB"

### ISSUE THREAD

**Issue by Srimrao02** [wso2/kubernetes-apim#200]
**Description:**
WSO api manager with analytics pod fails to start up with error pointing to synapse.xml not found, below is the log sample from the pod.

> [2019-06-12 12:41:52,624]  INFO - ServiceBusInitializer Starting ESB...
> [2019-06-12 12:41:52,649]  INFO - ServiceBusInitializer Initializing Apache Synapse...
> [2019-06-12 12:41:52,655]  INFO - SynapseControllerFactory Using Synapse home : /home/wso2carbon/wso2am-2.6.0/.
> [2019-06-12 12:41:52,656] **FATAL** - SynapseControllerFactory The synapse.xml location ././repository/deployment/server/synapse-configs/default doesn't exist
> [2019-06-12 12:41:52,656] **FATAL** - ServiceBusInitializer Couldn't initialize the ESB...
> org.apache.synapse.SynapseException: The synapse.xml location ././repository/deployment/server/synapse-configs/default doesn't exist
> 	at org.apache.synapse.SynapseControllerFactory.handleFatal(SynapseControllerFactory.java:121)
> 	at org.apache.synapse.SynapseControllerFactory.validatePath(SynapseControllerFactory.java:113)
> 	at org.apache.synapse.SynapseControllerFactory.validate(SynapseControllerFactory.java:88)
> 	at org.apache.synapse.SynapseControllerFactory.createSynapseController(SynapseControllerFactory.java:44)
> 	at org.apache.synapse.ServerManager.init(ServerManager.java:104)
> 	at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.initESB(ServiceBusInitializer.java:467)
> 	at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.activate(ServiceBusInitializer.java:206)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)

Our openshift cluster is in Azure, we are not using NFS server as a separate as persistent volumes are managed at azure. 
Nginx comes up, mysql DB service comes up but while deploying wso-apim-with-analytics component, pod gets created but throws this error.

Are we missing something here?

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** WSO 2.6.0

**OS, DB, other environment details and versions:**    mysql

**Steps to reproduce:**
Always, when we deploy using helm.

**Related Issues:**

**Comment by Srimrao02** [comment]
[wso2apim-with-analytics-apim-deployment-8cd6f877b-gmftv.log](https://github.com/wso2/kubernetes-apim/files/3301045/wso2apim-with-analytics-apim-deployment-8cd6f877b-gmftv.log)
Complete pod log

**Comment by Srimrao02** [comment]
Also wanted to update, when we remove below content from apim-with-analytics/templates/wso2apim-deployment.yaml and try to deploy, pod comes up without any issue.

```
          volumeMounts:
            - name: apim-storage-volume
              mountPath: /home/wso2carbon/wso2am-2.6.0/repository/deployment/server
            - name: apim-conf
              mountPath: /home/wso2carbon/wso2-config-volume/repository/conf
            - name: apim-conf-datasources
              mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/datasources
```

**Comment by Aaquiff** [comment]
I am working on Kubernetes resources to use Azurefiles for persistent storage on AKS through PR #199. While we will be merging this soon, if you could share your volume-claims manifests it could help narrow down the issue.

**Comment by Srimrao02** [comment]
@aaquiff thanks for the response, below is the volume-claims manifest.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2apim-with-analytics-apim-deployment-volume-claim
  namespace : {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: azure-standard

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2apim-with-analytics-tenants-volume-claim
  namespace : {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: azure-standard
```

**Comment by Aaquiff** [comment]
@Srimrao02 I can see two issues here assuming what you've provisioned here is an Azure disk..

- The disk you've provisioned might not have the permissions for the user wso2carbon(802).
- According to azure, "*An Azure disk can only be mounted with Access mode type ReadWriteOnce, which makes it available to only a single pod in AKS. If you need to share a persistent volume across multiple pods, use Azure Files*". This will be a problem when scaling your deployment.

I would suggest using Azure files either static or dynamic here to avoid these issues.
https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wso2
  name: endpoints-reader-role
rules:
- apiGroups: [""]
  verbs: ["get", "list"]
  resources: ["endpoints"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: wso2-endpoints-reader-role-binding
  namespace: wso2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoints-reader-role
subjects:
  - kind: ServiceAccount
    name: wso2svc-account
    namespace: wso2

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0700
  - file_mode=0700
  - uid=802
  - gid=802
parameters:
  skuName: Standard_LRS

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2apim-with-analytics-apim-deployment-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi

```
