### ISSUE TITLE
Helm chart for pattern 2 does not expose IS-KM to outside

### ISSUE THREAD

**Issue by rksk** [wso2/kubernetes-apim#310]
Helm chart for pattern 2 does not expose IS-KM to outside, therefore it is unable to use the IS only features by accessing the IS-KM nodes.

This can be fixed by adding adding ingress resouce as following to location `advanced/helm/am-pattern-2/templates/am-is-as-km/wso2am-pattern-2-is-as-km-ingress.yaml`

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wso2am-pattern-2-is-as-km-ingress
  namespace : {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  tls:
    - hosts:
        - {{ .Release.Name }}-is-as-km
  rules:
    - host: {{ .Release.Name }}-is-as-km
      http:
        paths:
          - path: /
            backend:
              serviceName: wso2am-pattern-2-km-service
              servicePort: 9443
```
