### ISSUE TITLE
[pattern2 - v3.2.0] Cannot borrow client for ssl://wso2am-pattern-2-am-2-service:9711

### ISSUE THREAD

**Issue by braccone** [wso2/kubernetes-apim#473]
**Description:**
Hi. When using pattern 2 for deploying the apim version 3.2.0, the pub-devportal-tm gives me the following error:
`
[2020-10-22 18:55:05,796]  INFO - DataBridge user admin connected
[2020-10-22 18:55:05,800] ERROR - Authenticator wrong userName or password
[2020-10-22 18:55:05,800] ERROR - DataEndpointConnectionWorker Error while trying to connect to the endpoint. Cannot borrow client for ssl://wso2am-pattern-2-am-2-service:9711.
org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Cannot borrow client for ssl://wso2am-pattern-2-am-2-service:9711.
        at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:145) ~[org.wso2.carbon.databridge.agent_5.2.26.jar:?]
        at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:59) [org.wso2.carbon.databridge.agent_5.2.26.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointLoginException: Error while trying to login to data receiver :wso2am-pattern-2-am-2-service/172.20.171.101:9711
        at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:50) ~[org.wso2.carbon.databridge.agent_5.2.26.jar:?]
        at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:139) ~[org.wso2.carbon.databridge.agent_5.2.26.jar:?]
        ... 6 more
Caused by: org.wso2.carbon.databridge.commons.exception.AuthenticationException: wrong userName or password
        at jdk.internal.reflect.GeneratedConstructorAccessor326.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryEventSender.processResponse(BinaryEventSender.java:163) ~[org.wso2.carbon.databridge.agent_5.2.26.jar:?]
        at org.wso2.carbon.databridge.agent.endpoint.binary.BinaryDataEndpoint.login(BinaryDataEndpoint.java:44) ~[org.wso2.carbon.databridge.agent_5.2.26.jar:?]
`

I think that the problem is related to this line **wrong userName or password**. I didn't find anything on wso2 documentation that tells me where to set the username and password for ssl in the configuration.
Thank you for your help

**Comment by scholtz** [comment]
hi @braccone .. 

check deployment.yaml file in wso2am-analytics-worker docker image..

```yaml

# Authentication configuration
auth.configs:
  type: 'local'        # Type of the IdP client used
  userManager:
    adminRole: admin   # Admin role which is granted all permissions
    userStore:         # User store
      users:
       -
         user:
           username: admin
           password: YWRtaW4=
           roles: 1
      roles:
       -
         role:
           id: 1
           displayName: admin
```

or check this file: https://github.com/wso2/kubernetes-apim/blob/master/advanced/am-pattern-2/templates/am-analytics/worker/wso2am-pattern-2-am-analytics-worker-conf.yaml or your config **wso2am-pattern-2-am-analytics-worker-conf**

then use it in wso2am deployment.toml
```
[apim.analytics]
enable = true
store_api_url = ".."
username = "admin"
password = "admin"
```
