### ISSUE TITLE
KeyManager service URL should be the k8s service name instead of localhost

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/kubernetes-apim#543]
**Description:**
Need $subjuect when configuring Choreo Connect as the gateway with APIM as the control plane.

In deployment toml file of `Single Node` and `Pattern1`, `service_url` of `[apim.key_manager]` is commented (using default).

```toml
    #[apim.key_manager]
    #service_url = "https://localhost:${mgt.transport.https.port}/services/"
```

Should be templated, for example in single node

```toml
  [apim.key_manager]
  service_url = "https://{{ template "am-single-node.resource.prefix" . }}-am-service.{{ .Release.Namespace }}:${mgt.transport.https.port}/services/"
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
