### ISSUE TITLE
Fix Readiness Probe

### ISSUE THREAD

**Issue by PasanT9** [wso2/kubernetes-apim#614]
**Description:**
We need to fix the Readiness Probe in all-in-one setup and GWs to following.

```
readinessProbe:
  httpGet:
    path: /api/am/gateway/v2/server-startup-healthcheck
    port: 9443
    scheme: HTTPS
```
