### ISSUE TITLE
Volume mount path mismatch in pattern-1 in master branch

### ISSUE THREAD

**Issue by imesh** [wso2/kubernetes-apim#62]
**Description:**
It seems like there is a mismatch between the volumes defined in the Analytics deployment definition and the init_carbon.sh in pattern 1 in the master branch:

wso2apim-analytics-1-deployment.yaml
````yaml
        volumeMounts:
          - name: apim-analytics-1-bin
            mountPath: "/home/wso2user/wso2am-analytics-2.1.0-conf/bin/"
          - name: apim-analytics-1-conf
            mountPath: "/home/wso2user/wso2am-analytics-2.1.0-conf/conf/"
          - name: apim-analytics-1-spark
            mountPath: "/home/wso2user/wso2am-analytics-2.1.0-conf/conf-analytics-spark/"
          - name: apim-analytics-1-axis2
            mountPath: "/home/wso2user/wso2am-analytics-2.1.0-conf/conf-axis2/"
          - name: apim-analytics-1-datasources
            mountPath: "/home/wso2user/wso2am-analytics-2.1.0-conf/conf-datasources/"
          - name: apim-analytics-1-tomcat
            mountPath: "/home/wso2user/wso2am-analytics-2.1.0-conf/conf-tomcat/"
````

init_carbon.sh:
````bash
if [ -e ${carbon_home}-conf/conf-analytics ]
 then cp ${carbon_home}-conf/conf-analytics/* ${carbon_home}/repository/conf/analytics/
fi
````

There is no volume mounted for folder "/home/wso2user/wso2am-analytics-2.1.0-conf/conf-analytics/" in the deployment.

[1] https://github.com/wso2/kubernetes-apim/blob/master/base/analytics/init_carbon.sh#L88
[2] ​https://github.com/wso2/kubernetes-apim/blob/master/pattern-1/artifacts/apim-analytics/wso2apim-analytics-1-deployment.yaml
