### ISSUE TITLE
Database Ready for Production Environment? 

### ISSUE THREAD

**Issue by marandalucas** [wso2/kubernetes-apim#82]
## Issue Description:

**The current WSO2’s repository has the kind property set as Deployment value. It is not a good practice to use Deployment with multiples Availability Zones with AWS block devices volumes (EBS). The reason is because the database POD could be recreated in other Availability Zone if it goes down, causing the POD can’t attach the volume again, since they’re resources attached just to one Availability Zones. This will cause the DB will get corrupted.**

**In the official documentation of kubernetes recommend to use Statefulset for these apps. IMPORTANT: StatefulSets are stable (GA) in 1.9.**
**https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/**

--------

**$ cat pattern-2/artifacts/rdbms/rdbms-deployment.yaml**
```
apiVersion: extensions/v1beta1 ## IMPORTANT: Not ready for production update the version of your Kubernetes Cluster.
kind: Deployment
metadata:
  name: apim-rdbms-deployment
  labels:
    app: apim-rdbms
    pattern: wso2apim-pattern-2
```

## Possible solution:
**To change the Deployment to Statefulset (stable version only in Kubernetes version 1.9.0)**

## Affected Product Version:
> branch master pattern-2

## OS, DB, other environment details and versions:  
- Cloud: Amazon Web Service
- Tool to Deploy Kubernetes in AWS: Kops Version 1.9.0
- Cluster Kubernetes version 1.9.3.
- Addon Kube-Ingress Controller v1.6.0.yaml

## Related Issues:
**Move from Deployment resource to StatefulSet resource** https://github.com/wso2/kubernetes-apim/issues/72
**Database Connectivity Issue: https://github.com/wso2/kubernetes-apim/issues/34**
